version: '2.1'

volumes:
  hango_sample_db_dev:
  hango_sample_node_modules:

services:
  db:
    image: mysql:5.7
    container_name: hango-mysql
    volumes:
      - ./db/config/utf-8.cnf:/etc/mysql/conf.d/custom.cnf
      - hango_sample_db_dev:/var/lib/mysql/
      - ./db/sql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hango
    command: 
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [CMD, mysqladmin ,ping, -h, localhost]
      timeout: 20s
      retries: 10

  hango:
    container_name: hango-server
    build:
      context: .
      dockerfile: ./compose/hango/Dockerfile-dev
    command: /start-dev.sh
    ports:
      - 9700:9700
    volumes:
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./server/server.js:/app/server.js
      - ./server/.eslintrc.js:/app/.eslintrc.js
      - ./server/.prettierrc.json:/app/.prettierrc.json
      - hango_sample_node_modules:/app/node_modules
    environment:
      - DB_HOST=mysql
      - DB_NAME=hango
      - DB_USER=root
      - DB_PASSWORD=password
      # - HANGO_MANAGER_EMAIL=YOUR_EMAIL_ADDRESS        # -> https://myaccount.google.com/lesssecureapps 해당 사이트에서 액세스를 허용시켜주어야 합니다.
      # - HANGO_MANAGER_PASSWORD=YOUR_EMAIL_PASSWORD    # -> 위 사이트에서 액세스를 허용시켜주어야 합니다. 해당 Gmail로 Hango 관리자 회원가입 승인 요청이 전달됩니다.
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:mysql
